version: '1'
services:
  simulator:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - ./sim_rooms:/app/sim_rooms
    # environment:
      # - FLASK_APP=sim:app
    # command: ["pipenv", "run", "gunicorn", "--worker-class", "eventlet", "-w", "1", "sim:app"]
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env