services:
    simulator:
        environment:
            - CMD=uv run flask --app sim:app --debug run --host=0.0.0.0 --port=8069
            - DEBUG=1
        develop:
            watch:
                - action: sync
                  path: ./app
                  target: /app
