services:
    test_server:
        restart: unless-stopped
        build:
            context: app
            dockerfile: Dockerfile
        ports:
            - "8666:8069"
        volumes:
            - ./sim_rooms:/app/sim_rooms
        environment:
            - CMD=uv run gunicorn -b 0.0.0.0:8069 --worker-class eventlet -w 1 wsgi:app
            - DEBUG=0
            - SIM_SECRETKEY="test-secret-key"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:8069"]
            interval: 5s
            timeout: 4s
            retries: 5
            start_period: 10s
            start_interval: 2s
    test_runner:
        depends_on:
            test_server:
                condition: service_healthy
        build:
            context: app
            dockerfile: Dockerfile
        volumes:
            - ./sim_rooms:/app/sim_rooms
        environment:
            - CMD=uv run python -m pytest
        env_file:
            - .env
