services:
    simulator:
        build:
            context: app
            dockerfile: Dockerfile
            target: base_server
        restart: unless-stopped
        ports:
            - "8069:8069"
        volumes:
            - ./sim_rooms:/sim_rooms
        environment:
            - SIM_ROOM_STORE=/sim_rooms
            - RATELIMIT_ENABLED=1
        env_file:
            - .env
        labels:
            - dev.orbstack.domains=sim.local
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:8069"]
            interval: 5s
            timeout: 4s
            retries: 5
            start_period: 10s
            start_interval: 2s
    tunnel:
        image: cloudflare/cloudflared:latest
        restart: unless-stopped
        command: tunnel --no-autoupdate run
        env_file:
            - .env
