services:
  simulator:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - ./sim_rooms:/app/sim_rooms
    environment:
      - CMD=pipenv run gunicorn -b 0.0.0.0:8069 --worker-class eventlet -w 1 sim:app
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env