services:
    test-server:
        build:
            target: dev_server
        restart: unless-stopped
        volumes:
            - ./sim_rooms:/sim_rooms
        environment:
            - SIM_SECRETKEY="test-secret-key"
            - SIM_ROOM_STORE=/sim_rooms
            - RATELIMIT_ENABLED=0
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:8069"]
            interval: 5s
            timeout: 4s
            retries: 5
            start_period: 10s
            start_interval: 2s
    test-runner:
        build:
            target: test_runner
        volumes:
            - ./sim_rooms:/sim_rooms
        environment:
            - SIM_SECRETKEY="test-secret-key"
            - SIM_TEST_SERVER_ADDR=http://test-server:8069
            - SIM_ROOM_STORE=/sim_rooms
            - RATELIMIT_ENABLED=0
        depends_on:
            test-server:
                condition: service_healthy
    test-runner-headed:
        build:
            target: test_runner_headed
        ports:
            - "5901:5900"
        volumes:
            - ./sim_rooms:/sim_rooms
        environment:
            - SIM_SECRETKEY="test-secret-key"
            - SIM_TEST_SERVER_ADDR=http://test-server:8069
            - SIM_ROOM_STORE=/sim_rooms
            - RATELIMIT_ENABLED=0
            - VNC_PASSWORD=sim
        depends_on:
            test-server:
                condition: service_healthy
