services:
  simulator:
    environment:
      - CMD=pipenv run flask --app sim:app --debug run --host=0.0.0.0 --port=8069
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
  tunnel:
    env_file:
      - .devenv