services:
    simulator:
        build:
            target: dev_server
        environment:
            - RATELIMIT_ENABLED=0
        develop:
            watch:
                - action: sync
                  path: ./app
                  target: /simulator/app
